app = "deepdip2"
primary_region = "ams"

[build]
  image = "ghcr.io/denoland/denokv:latest"

[http_service]
  internal_port = 4512
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  DENO_KV_SQLITE_PATH="/data/denokv.sqlite3"

[mounts]
  destination = "/data"
  source = "denokv_data"

[[vm]]
  size = 'shared-cpu-1x'
